apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  namespace: node-app
  labels:
    app: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      name: node-app
      namespace: node-app
      labels:
        app: node-app
    spec:
      containers:
      - name: node-container
        image: ashu2903/node-app-batch-6
        ports:
          - containerPort: 8000
        resources:
          requests:
            memory: "64Mi"
            cpu: "240m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        


